version: '3.9'
services:
  db:
    image: mysql:8.0.32
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: docker
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - taskManager-network
  task-manager-directory:
    image: vinicius14/task-manager
    restart: always
    build: ./task-manager-directory
    working_dir: /task-manager-directory
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/task_manager?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 1234
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - taskManager-network
networks:
  taskManager-network:
    driver: bridge